### ISSUE TITLE
Refactor the repository

### ISSUE THREAD

**Issue by makimenko** [makimenko/angular-template-for-threejs#12]
**Considered**
1. Considering repository analytics, it seems that "threejs" branch is noticeable popular (95% of visits). The rest branches are not so popular.
2. The initial idea of repository was to create atomic templates (charts, auth0, admin, material design, threejs etc). It seems that "schematics-cli" (which appeared after repo creation) is more suitable for such atomic templates. In addition the rest branches are outdated.
3. repo postfix "for-dummies" is not reflecting the truth. The repo content is more for experienced users.

**Proposal**
1. merge threejs branch to master
2. [rename repository](https://help.github.com/en/articles/renaming-a-repository) to "angular-template-for-threejs" (old URLs will be backward compatible and redirected to new repo)
3. update readme/project description
4. modify threejs scene a bit + will make it as demo in gh-pages

@ComFreek what you think about it? Would you mind if I will do it?

**Comment by ComFreek** [comment]
> repo postfix "for-dummies" is not reflecting the truth. The repo content is more for experienced users.

Hah 😄 I actually like reading "for dummies" in descriptions of tutorials. It also guarantees most of the time that the solution can be *quickly* applied instead of wasting hours of going through building instructions. However, "angular-template-for-threejs-for-dummies" would be too long, so yes, I'd agree with "angular-template-for-threejs". Maybe retain "for dummies" in the readme?

I think the old [angular-three-examples](https://github.com/makimenko/angular-three-examples) repo should also forward to this - once renamed - one. I am not sure whether you want to retain the Angular 5 version, maybe as an (orphaned) branch of this repo? By the way, this old repo is a superb Google hit for the search text "angular template threejs", so we should be cautious with moving/renaming it. Apparently "three examples" is a good phrase for Google to find it as well.

> It seems that "schematics-cli" (which appeared after repo creation) is more suitable for such atomic templates.

Oh I didn't know about that one. Would it worth providing threejs and also the other branches as schematics? But I'd also opt for retaining a functional ready-to-download version of threejs. It helped me a lot previously to get a basic setup running.

> @ComFreek what you think about it? Would you mind if I will do it?

Go ahead 👍 Let me know if I can help somewhere.

**Comment by makimenko** [comment]
Should be good, Please check.
NOTE: Clean install (delete node_modules, then npm i) is required.

> Maybe retain "for dummies" in the readme?
Yep, remains in readme

> old angular-three-examples repo should also forward to this - once renamed
Yep, will think about it. Can't find how to redirect yet.

> whether you want to retain the Angular 5 version, maybe as an (orphaned) branch of this repo
Would be nicer and cleaner to get rid of 2 repos.. But.... seems old repo has nice amount of stars :) and don't want to loose it. Will think...

**Comment by ComFreek** [comment]
> Should be good, Please check.
NOTE: Clean install (delete node_modules, then npm i) is required.

Did a complete clean clone and install and works! 🎆 

> But.... seems old repo has nice amount of stars :) and don't want to loose it. Will think...
That's understandable. You could also "archive" that repository and add big links to this one.

By the way, there is an unrelated project called Chocolatey (a package manager). Previously, it had the repository `github.com/chocolatey/chocolatey`, then it switched to `github.com/chocolatey/choco` while the former wasn't deleted. I disliked very much that Google always displayed the results for the old repo above the one for the new one. Every time I searched for "chocolatey wiki", I got to the GitHub wiki of the old repo.
I am not sure how much of an issue that is for this project since using this project is more of a "once-read, once-install, once-use" scenario whereas as a package maintainer one has to repeatedly look up Chocolatey documentation.

**Comment by makimenko** [comment]
Moved "angular-three-examples" project to Archive.
Hope it will adjust Google's search priorities. 
If not, then will delete old repo later (just need to update some stackoverflow etc. references first).
