### ISSUE TITLE
Object Selection

### ISSUE THREAD

**Issue by sdavarifard** [makimenko/angular-template-for-threejs#36]
Hi,
how to select objects and get information?

**Comment by makimenko** [comment]
Hello,
Raycaster class is designed to assist with raycasting, which is used for mouse picking (working out what objects in the 3d space the mouse is over) amongst other things.

https://threejs.org/docs/#api/en/core/Raycaster

```
// calculate objects intersecting the picking ray
var intersects = raycaster.intersectObjects( scene.children );
```

**Comment by sdavarifard** [comment]
Hello,
thank you and it is working now , but for all Objects intersect[0].object.type is "Mesh".
how to get real Object type ex: cylinder, cube ...

**Comment by ComFreek** [comment]
Could you show us more code, please?

Also, have you seen the [Three.js example "interactive cubes"](https://threejs.org/examples/#webgl_interactive_cubes) ([source here](https://github.com/mrdoob/three.js/blob/master/examples/webgl_interactive_cubes.html))?

**Comment by sdavarifard** [comment]
all in webgl-render : 

`  private mouse = new THREE.Vector2(); INTERSECTED ;
  private raycaster = new THREE.Raycaster();

@HostListener('click', ['$event']) //document:keypress
  public onKeyPress(event: MouseEvent) {
    this.mouse.x = ( event.clientX / window.innerWidth ) * 2 - 1;
    this.mouse.y = - ( event.clientY / window.innerHeight ) * 2 + 1;
    this.myRaycaster();
  }

private myRaycaster(){
      const sceneComponent = this.sceneComponents.first;
      const cameraComponent = this.cameraComponents.first;
      var vector = new THREE.Vector3(( this.mouse.x / window.innerWidth ) * 2 - 1, -( this.mouse.y / window.innerHeight ) * 2 + 1, 0.5);
      vector = vector.unproject(cameraComponent.camera);

      // update the picking ray with the camera and mouse position
	    this.raycaster.setFromCamera( this.mouse, cameraComponent.camera );

	    // calculate objects intersecting the picking ray
      var intersects = this.raycaster.intersectObjects( this.sceneComponents.first.getObject().children, true );
      
      if(intersects.length>0){
      	if ( this.INTERSECTED != intersects[ 0 ].object ) {
          if ( this.INTERSECTED ) 
          this.INTERSECTED = intersects[ 0 ].object;
          if(intersects[ 0 ].object.type == "Mesh"){
            this.INTERSECTED = intersects[ 0 ].object;
            this.INTERSECTED.material.emissive.setHex( 0xff0000 );
            this.render();
          }
        }
      } else {
        if ( this.INTERSECTED ) 
        this.INTERSECTED = null;
      }
  }
`

**Comment by ComFreek** [comment]
I set up a minimal working bench to test this on the `raycaster-test` branch.
However, I also can't get it to work. The relevant changes are here:
https://github.com/makimenko/angular-template-for-threejs/blob/a59ff9dd1b3fb2718f51c0f0565a4d62ed631e75/src/app/app.component.ts#L38-L49
The code above always returns an empty array for intersected objects. If I intersect with all of the scene's children (i.e. `relevantObjects` without the filtering), then I always get intersected objets of type `linesegment`.

**Comment by sdavarifard** [comment]
because of this `true`
> const intersectedObjects = this.raycaster.intersectObjects(relevantObjects, true);

_If true, it also checks all descendants. Otherwise it only checks intersection with the object. Default is false._

**Comment by ComFreek** [comment]
@sdavarifard Thanks, that was the issue! My test now works: https://github.com/makimenko/angular-template-for-threejs/commit/5cc24cd3798a8c717a0309102c544475943a1454.

Build instructions as in README: npm install, ng build atft, ng serve --open
Usage: right-click some of the cubes, then move the camera with the left mouse button*

*) to force rerendering. Sadly, I could not get ViewChild to work with the WebGLRenderingComponent, I always got the error "Can't construct a query for the property, since the query selector wasn't defined".

**Comment by sdavarifard** [comment]
how to show selected Object info. in new ShowDialog?

**Comment by ComFreek** [comment]
@sdavarifard Which "ShowDialog" are you referring to? I know none and could not find one on the Internet (with keywords 'JS' and 'Three.js').

**Comment by sdavarifard** [comment]
Sorry that my question was unclear... I am new in NG and threejs.
What I would do:
1- Click on Obj --> get Object's Info (Done)
2- Display for Example Object name,id... (selected) in new Window or Dialog such : [MatDialog](https://material.angular.io/components/dialog/overview) in ng

**Comment by ComFreek** [comment]
Instead of `console.log` (as shown in my `raycaster-test` branch), you would need to populate information for your `MatDialog`. I would imagine this as setting some property of a `MatDialog` ViewChild and then possibly triggering Angular's change detection. However, I am not actively using Angular at the moment and thus can't give you any more concrete example.

But if you come up with a minimal example, feel free to share if you want. Maybe we could integrate it in `atft`'s showcase example.


Closing this thread unless there's more to discuss/ask. Feel free to request reopening.

**Comment by sdavarifard** [comment]
yes , done with Send intersected Obj to Parent . thank you.
