### ISSUE TITLE
raycaster-test branch: `this.cameraDirective is undefined`

### ISSUE THREAD

**Issue by sdavarifard** [makimenko/angular-template-for-threejs#47]
ERROR TypeError: "this.cameraDirective is undefined"
I think because ViewChild is called AfterInit but Hostlistener by OnInit...? 
`@ViewChild(PerspectiveCameraDirective)
  private cameraDirective: PerspectiveCameraDirective;`

`  @HostListener('click')
  shoutClickedObject() {
    this.raycaster.setFromCamera(this.mousePosition, this.cameraDirective.camera);
   ...
  }`

**Comment by ComFreek** [comment]
For reference, this code stems from my [`raycaster-test` branch](https://github.com/makimenko/angular-template-for-threejs/tree/raycaster-test).

I assume you the error occurs after clicking, right? Do you perform the click right the page load or after a few seconds?

**Comment by sdavarifard** [comment]
no, actually the error occurs during page initial and also after a few seconds.
but, if write all (click Hostlistener) in webgl-renderer.component, works well.

**Comment by ComFreek** [comment]
> but, if write all (click Hostlistener) in webgl-renderer.component, works well.

I cannot fully imagine the code change in my mind. Could you please post the relevant code diff? I try to have a look in a few days, can't promise anything sooner. Perhaps, you could try your luck in Angular forums/chats with a pinpointed example?

@makimenko Random idea: should we provide a playground plunkr with the same contents as the template from this repository? So that people could directly play with it and also seek help faster. What do you think?

**Comment by makimenko** [comment]
Hi 

> should we provide a playground plunkr with the same contents as the template from this repository

Indeed. Good idea

**Comment by ComFreek** [comment]
Closing as no feedback from issue creator. @sdavarifard I am happy to reopen this if you desire further discussion :smile:
