### ISSUE TITLE
Replace demo template by Showcase

### ISSUE THREAD

**Issue by makimenko** [makimenko/angular-template-for-threejs#96]
Thanks to functionality introduced by Storybook, we have now good component development tool and very nice component showcase demonstration. Demo app becomes a bit useless.

@ComFreek Some time ago you proposed to remove app / demo template and keep only library in this repository. I think now we can do it. What do you think?

Planned tasks:
- Replace gh-pages demo to Storybook
- Remove root app and keep only projects/atft
- Modify API Docs: Generate docs for atft library
- Adjust pipeline
- Update readme

Creation of separate repo with project template => don't think it's really needed, considering standard atft library. Readme sample should be enough.

**Comment by ComFreek** [comment]
Good idea!

The only thing I am **missing from Storybook** is the option to show the corresponding source code. Is this doable somehow?

> Replace gh-pages demo to Storybook

I'd still put the deploy storybook into `./storybook` on gh-pages and deploy the API documentation to `./` on gh-pages. Since the API documentation still shows the repo README, e.g. click on https://makimenko.github.io/angular-template-for-threejs/.

> Creation of separate repo with project template => don't think it's really needed, considering standard atft library. Readme sample should be enough.

Yep + link to storybook.

What about people who just want to download/clone a repo and get instantly running after `npm install`? I would see how many steps are needed in the new approach. (Particularly, I am myself sometimes like this and skip to the next opensource library if I can't get the first running in <= some minutes -- or at least if I don't get a feel for how many steps are needed.)

**Comment by makimenko** [comment]
> show the corresponding source code

will check

> I'd still put the deploy storybook into ./storybook

Ok

> people who just want to download/clone a repo

Yeah... Then let's keep AppComponent here for time being.
